"""pass reset

Revision ID: ed4eb26dae61
Revises: password_reset_requests
Create Date: 2025-11-18 17:39:38.548021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4eb26dae61'
down_revision = 'password_reset_requests'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_password_reset_requests_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_requests_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
